Use bytes instead of string in librsync modules.
Get rid of:
  File "build/lib.linux-x86_64-3.7/rdiff_backup/librsync.py", line 87, in _add_to_outbuf_once
    try: self.eof, len_inbuf_read, cycle_out = self.maker.cycle(self.inbuf)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 7: invalid continuation byte