Return 0 instead of None if there is no last commit
Gets rid of:
  File "/home/ericl/Public/rdiff-backup/build/lib.linux-x86_64-3.7/rdiff_backup/Main.py", line 503, in backup_final_init
    if prevtime >= Time.curtime: Log.FatalError(
TypeError: '>=' not supported between instances of 'NoneType' and 'int'