Return Iterate_fast generator instead of self in self_unc
Gets rid of:
  File "/home/ericl/Public/rdiff-backup/build/lib.linux-x86_64-3.7/rdiff_backup/fs_abilities.py", line 533, in set_resource_fork_readonly
    for rp in selection.Select(dir_rp).set_iter():
TypeError: 'Select' object is not iterable