Use bytes when setting chars_to_quote in case file doesn't exist in repo (#163)
Fixes following error:
  [...]
  File .../rdiff_backup/fs_abilities.py, line 769, in set_compatible_timestamps
    if Globals.chars_to_quote.find(b:) > -1:
  TypeError: must be str, not bytes