Differentiate better strings from bytes vs. old data
Get rids of:
  File "/home/ericl/Public/rdiff-backup/build/lib.linux-x86_64-3.7/rdiff_backup/rpath.py", line 1210, in write_string
    outfp.write(s)
TypeError: a bytes-like object is required, not 'str'