Avoid failing when trying to kill non-existing pid
Gets rid of:
  File "backup/build/lib.linux-x86_64-3.7/rdiff_backup/regress.py", line 349, in pid_running
    if exc[0] == errno.ESRCH: return 0
TypeError: 'ProcessLookupError' object is not subscriptable